name: Deploy_to_Azure
run-name: terraform_plan

on: 
  push:
    branches:
      - master
      - feature-*
      
  pull_request:
    branches:
      - master
    
permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: az login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: terraform_init
        run: terraform init

      - name: validate
        run: terraform validate

      - name: terraform_plan
        run: terraform plan

  terraform_apply:
    #if: ${{ needs.terraform_plan.result == 'success' && github.ref == 'refs/heads/master' }}
    needs: terraform_plan
    runs-on: self-hosted
    environment: approver
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: terraform_init
        run: terraform init
      - name: terraform_apply
        run: terraform apply --auto-approve

